ruby/rails/blog/config/routes.rb
Rails.application.routes.draw do

   root 'home#index'

     resources :articles

end

ruby/rails/blog/app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3 }
end

ruby/rails/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        
    end
    def create
        @article = Article.new(article_params)
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def show
        @article = Article.find(params[:id])
    end
    # def index
        
    # end
    private
        def article_params
            params.require(:article).permit(:title, :content)
        end
end

ruby/rails/blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

ruby/rails/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

ruby/rails/blog/app/helpers/home_helper.rb
module HomeHelper
end

ruby/rails/blog/app/views/articles/index.html.erb
<html>
<head>
	<title>Article Index</title>
</head>
<body>
	<h1>Hello, Rails!</h1>
	<%= link_to 'My Blog', controller: 'articles' %>

	<%= link_to 'New article', new_article_path %>
</body>
</html>

ruby/rails/blog/app/views/articles/new.html.erb
<html>
<head>
	<title>New Articles</title>
</head>
<body>
	<h2> <font color="red">New Articles</font></h2>
	
	<%= form_for :article, url: articles_path do |f| %>
		<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@article.errors.count, "error") %> prohibited
			this article from being saved:</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :text %><br>
			<%= f.text_area :text %>
		</p>

		<p>
			<%= f.submit %>
		</p>
	<% end %>
	 
	<%= link_to 'Back', articles_path %>
</body>
</html>

ruby/rails/blog/app/views/articles/show.html.erb
<html>
<head>
	<title><%= @article.title %></title>
</head>
<body>
	<p>
		<strong>Title:</strong>
		<%= @article.title %>
	</p>

	<p>
		<strong>Text:</strong>
		<%= @article.content %>
	</p>
	<p>
		<strong>Created_at:</strong>
		<%= @article.created_at.strftime("%H:%M:%S %A  %Z") %>
	</p>
	<p>
		<strong>Update_at:</strong>
		<%= @article.updated_at %>
	</p>
 
	<%= link_to 'Back', articles_path %>
</body>
</html>

ruby/rails/blog/app/views/home/index.html.erb
<html>
<head>
	<title>Welcome</title>
</head>
<body>
	<h2><font color="red">Welcome</font></h2>
</body>
</html>

ruby/rails/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>