ruby/rails/depot/config/routes.rb
Rails.application.routes.draw do
  get 'store/index'

  resources :products

  root :to => "store#index", :as => 'store'

end

ruby/rails/depot/app/models/product.rb
class Product < ActiveRecord::Base

    default_scope { order( 'price') }

    validates :title, :description, :image_url, :presence => true
    validates :price , :numericality => {:greater_than_or_equal_to => 0.01}
    validates :title, :uniqueness => true
    validates :image_url, :format => {
        :with      => %r{\.(gif|jpg|png)\z}i,
        :message     => "must be a URL for GIF, IPG or PNG images"
    }

end

ruby/rails/depot/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby/rails/depot/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

ruby/rails/depot/app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.all
  end
end

ruby/rails/depot/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/rails/depot/app/helpers/products_helper.rb
module ProductsHelper
end

ruby/rails/depot/app/helpers/store_helper.rb
module StoreHelper
end

ruby/rails/depot/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>CJStudio.org</title>
		<meta name="author" content="cjstudio" />
		<meta name="description" content="This is cjstudio's blog website" />
		<%= stylesheet_link_tag 'scaffold' %>
		<%= stylesheet_link_tag 'depot', :media => 'all' %>
		<%= javascript_include_tag :default %>
		
		<!-- 
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
		<%= csrf_meta_tags %>
	</head>
	<body> 
		<div align="center">
		<%= yield %>
		</div>
	</body>
</html>

ruby/rails/depot/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/rails/depot/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

ruby/rails/depot/app/views/products/index.html.erb
<h1>Listing products</h1>
<table>

    <% @products.each do |product| %>
    <% @table_tr_odd = false 
      @table_tr_i = !@table_tr_i
    %>
      <tr class="<%= "isOdd_#{@table_tr_i}" %>">

        <td><%= image_tag(product.image_url,:class => 'list_image') %></td>
        <td>
          <dl>
            <dt id="td_product_title"><strong><%= product.title %></strong></dt>
            <dt id="td_product_description"><%= product.description %></dt>
          </dl>
        </td>
        <td><p id="td_product_price"><%= number_to_currency(product.price) %></p></td>
        <td><p id="td_product_timestamp"><%= product.created_at %></p></td>
        <td><p id="td_product_timestamp"><%= product.updated_at %></p></td>
        <td>
          <dl>
            <dt><%= link_to 'Show', product %></dt>
            <dt><%= link_to 'Edit', edit_product_path(product) %></dt>
            <dt><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></dt>
          </dl>
          
          
        </td>
      </tr>
    <% end %>
</table>
<br>

<%= link_to 'New Product', new_product_path %>

ruby/rails/depot/app/views/products/new.html.erb
<h1>New product</h1>

<div class="new_form">
	<%= render 'form' %>
</div>

<%= link_to 'Back', products_path %>

ruby/rails/depot/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

ruby/rails/depot/app/views/store/index.html.erb
<% if true %>
	<p id="notice"></p>
<% end %>

<h1> Your Pragmatic Catalog</h1>
	
<table>	
    <% @products.each do |product| %>
    <% @table_tr_odd = false 
      @table_tr_i = !@table_tr_i
    %>
      <tr class="<%= "isOdd_#{@table_tr_i}" %>">
        <td><%= image_tag(product.image_url,:class => 'list_image') %></td>
        <td>
          <dl>
            <dt id="td_product_title"><strong><%= product.title %></strong></dt>
            <dt id="td_product_description"><%= product.description %></dt>
          </dl>
        </td>
        <td>
        	<span id="td_product_price"><%= number_to_currency(product.price) %></span>
        </td>
      </tr>
<% end %>
</table>